### ISSUE TITLE
mne_icalabel ImportError

### ISSUE THREAD

**Issue by Zoora00** [mne-tools/mne-icalabel#177]
Traceback (most recent call last):
  File "D:\yan\EEG\多模态\3.25\SI-CLEER-main\DEAP\preprocess_data_remove_artefacts.py", line 11, in <module>
    from mne_icalabel import label_components
  File "C:\Users\Lenovo\.conda\envs\env_tracker\lib\site-packages\mne_icalabel\__init__.py", line 5, in <module>
    from . import features  # noqa: F401
  File "C:\Users\Lenovo\.conda\envs\env_tracker\lib\site-packages\mne_icalabel\features\__init__.py", line 3, in <module>
    from .topomap import get_topomaps  # noqa: F401
  File "C:\Users\Lenovo\.conda\envs\env_tracker\lib\site-packages\mne_icalabel\features\topomap.py", line 6, in <module>
    from mne.io import Info
ImportError: cannot import name 'Info' from 'mne.io' (C:\Users\Lenovo\.conda\envs\env_tracker\lib\site-packages\mne\io\__init__.py)

**Comment by mscheltienne** [comment]
Closing, you are running on an old version of `mne-icalabel` with a new version of `mne`.
See: https://github.com/mne-tools/mne-icalabel/blob/512312bfd44ea26eb33a9a2190ed175fcfd87353/mne_icalabel/features/topomap.py#L1-L25

Where the import `from mne.io import Info` is not present anymore.
Please upgrade both `mne` and `mne-icalabel` to their latest stable version.

Tested with:
- `mne` 1.6.1 and `mne-icalabel` 0.6.0 (stable)
- `mne` 1.6.1 and `mne-icalabel` 0.7.0.dev0 (main)
